WebApplication1/Controllers/BookingController.cs
using Artistic_Showroom_Web.Models;
using Domain.Entities;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BookingController : Controller
    {

        BookingService BS = new BookingService();
        UserService US = new UserService();
        EventServices ES = new EventServices();

        //GET : ListEvent
        public ActionResult GetListEvent()
        {
            List<EventViewModels> eventList = new List<EventViewModels>();

            foreach (var item in ES.GetAll())
            {       

                EventViewModels EVM = new EventViewModels();
               
                    EVM.eventId = item.eventId;
                    EVM.statEvent = item.statEvent;
                    EVM.userId = item.userId;
                    EVM.title = item.title;
                    EVM.description = item.description;
                    EVM.inclusions = item.inclusions;
                    EVM.startDate = item.startDate;
                    EVM.actualDate = DateTime.Now;
                    EVM.endDate = item.endDate;
                    EVM.imageURL = item.imageURL;
                    EVM.nbParticipant = item.nbParticipant;
                    eventList.Add(EVM);

                
            }

            return View(eventList);
        }

        //GET : ParticipantList
        public ActionResult GetParticipateUsers(int id)
        {
            List<UserViewModel> ListUsers = new List<UserViewModel>();

            foreach (var item in BS.getUsersParticipate(id))
            {
                User u = US.GetById(item);

                UserViewModel UVM = new UserViewModel();

                    UVM.firstName = u.firstName;
                    UVM.lastName = u.lastName;
                     UVM.email = u.email;
                    ListUsers.Add(UVM);

                }
            return View(ListUsers);
        }

            
        

        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }

        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/CalendarController.cs
using Domain.Entities;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    //[Authorize(Roles ="Client")]
    public class CalendarController : Controller
    {

        EventServices ES = new EventServices();
        // GET: Calendar
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {

            var events = ES.GetAll();
            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }

        [HttpPost]
        public JsonResult SaveEvent(Event e)
        {
            var status = false;
            
                if (e.eventId > 0)
                {
                    //Update the event
                    var v = ES.GetAll().Where(a => a.eventId == e.eventId).FirstOrDefault();
                    if (v != null)
                    {
                        v.title = e.title;
                        v.description = e.description;
                        v.startDate = e.startDate;
                        v.endDate = e.endDate;
                        v.inclusions = e.inclusions;
                        v.actualDate = DateTime.Now;
                  
                }
                }
                else
                {
                    ES.Add(e);
                }
                ES.Commit();
                status = true;
            

            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventId)
        {
            var status = false;
            
                var v = ES.GetAll().Where(a => a.eventId == eventId).FirstOrDefault();
                if (v != null)
                {
                    ES.Delete(v);
                    ES.Commit();
                    status = true;
                }
            
            return new JsonResult { Data = new { status = status } };
        }

        // GET: Calendar/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Calendar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calendar/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calendar/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Calendar/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Calendar/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Calendar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/EventController.cs
using Artistic_Showroom_Web.Models;

using Domain.Entities;

using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Drawing;
using WebApplication1.Helpers;
using System.Net.Mail;
using System.Text;
using System.Drawing.Printing;
using System.Diagnostics;

namespace Artistic_Showroom_Web.Controllers
{
    public class EventController : Controller
    {
        EventServices ES = null;
        GalleryService GS = new GalleryService();
        UserService US = new UserService();
        BookingService BS = new BookingService();
        public EventController()
        {
            ES = new EventServices();      

        }
    

        //GET : Event
        public ActionResult Index()
        {
            List<EventViewModels> eventList = new List<EventViewModels>();

            foreach (var item in ES.GetAll())
            {
                if (item.endDate < DateTime.Now)
                {
                    ES.changeStateEvent(item);
                }

                EventViewModels EVM = new EventViewModels();

                if (item.statEvent == "UpComing")
                {

                    EVM.eventId = item.eventId;
                    EVM.userId = item.userId;
                    EVM.title = item.title;
                    EVM.description = item.description;
                    EVM.inclusions = item.inclusions;
                    EVM.startDate = item.startDate;
                    EVM.actualDate = DateTime.Now;
                    EVM.endDate = item.endDate;
                    EVM.imageURL = item.imageURL;
                    EVM.nbParticipant = item.nbParticipant;
                    eventList.Add(EVM);

                }

            }

            return View(eventList);


        }


        // GET : Event/Details
        public ActionResult Details(int id)
        {
            EventViewModels EVM = new EventViewModels();
            Event e = ES.GetById(id);
            EVM.eventId = e.eventId;
            EVM.title = e.title;
            EVM.description = e.description;
            EVM.inclusions = e.inclusions;
            EVM.startDate = e.startDate;
            EVM.actualDate = e.actualDate;
            EVM.endDate = e.endDate;
            EVM.statEvent = e.statEvent;
            EVM.nbParticipant = e.nbParticipant;

            return View(EVM);
        }

        // GET : Event/Create
        public ActionResult Create()
        {
            EventViewModels GVM = new EventViewModels();
            GVM.galleries = ES.GetAllGalleries().ToSelectListItems();
           
            
            return View(GVM);
           
        }

        // POST : Event/Create
        [HttpPost]
        public ActionResult Create(EventViewModels EVM, HttpPostedFileBase Image1)
        {
            if (!ModelState.IsValid || Image1 == null || Image1.ContentLength == 0)
            {
                RedirectToAction("Create");
            }
            EVM.imageURL = Image1.FileName;




            Event e = new Event();
            e.title = EVM.title;
            e.description = EVM.description;
            e.inclusions = EVM.inclusions;
            e.startDate = EVM.startDate;
            e.actualDate = DateTime.Now ;
            e.endDate = EVM.endDate;
            e.GalleryId = EVM.galleryId;
            e.statEvent = "UpComming";
            e.userId = 1;

            e.imageURL = EVM.imageURL;
            e.nbParticipant = EVM.nbParticipant;

            ES.Add(e);
            ES.Commit();

            // Sauvgarde de l'image

            var path = Path.Combine(Server.MapPath("~/Content/Upload/"), Image1.FileName);
            Image1.SaveAs(path);

            return RedirectToAction("Details", new { id = e.eventId});            

        }

        //GET: Event/Edit/5
        public ActionResult Edit(int id)
        {
            EventViewModels PVM = new EventViewModels();
            Event p = ES.GetById(id);
            PVM.eventId = p.eventId;
            PVM.title = p.title;
            PVM.description = p.description;
            PVM.startDate = p.startDate;
            PVM.actualDate = p.actualDate;
            PVM.endDate = p.endDate;
            PVM.inclusions = p.inclusions;
            PVM.nbParticipant = p.nbParticipant;

            if (PVM == null)
            {
                return HttpNotFound();
            }
            return View(PVM);

          
        }

        // POST: Event/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EventViewModels EVM)
        {
            Event e = ES.GetById(id);
            e.title = EVM.title;
            e.description = EVM.description;
            e.inclusions = EVM.inclusions;
            e.startDate = EVM.startDate;
            e.actualDate = EVM.actualDate;
            e.endDate = EVM.endDate;
            e.nbParticipant = EVM.nbParticipant;

            ES.Update(e);
            ES.Commit();
            return RedirectToAction("Details", new { id = e.eventId });
        }

        // GET: Event/Delete/1
        public ActionResult Delete(int id)
        {

            EventViewModels EVM = new EventViewModels();
            Event e = ES.GetById(id);
            EVM.eventId = e.eventId;
            EVM.title = e.title;
            EVM.description = e.description;
            EVM.inclusions = e.inclusions;
            EVM.startDate = e.startDate;
            EVM.actualDate = e.actualDate;
            EVM.endDate = e.endDate;
            EVM.nbParticipant = e.nbParticipant;

            if (EVM == null)
            {
                return HttpNotFound();
            }
            return View(EVM);

        }


        //POST: Event/Delete/1
        [HttpPost]
        public ActionResult Delete(int id, EventViewModels EVM)
        {
            Event e = ES.GetById(id);
            
            e.title = EVM.title;
            e.description = EVM.description;
            e.inclusions = EVM.inclusions;
            e.startDate = EVM.startDate;
            e.actualDate = EVM.actualDate;
            e.endDate = EVM.endDate;
            e.nbParticipant = EVM.nbParticipant;

            ES.Delete(e);
            ES.Commit();
            return RedirectToAction("Index");

        }

      

        // GET: Event/Paricipate/1
        public ActionResult Participate(int id)
        {

            
            //Booking b = .GetById(id);
            //EVM.eventId = e.eventId;
            //EVM.title = e.title;
            //EVM.description = e.description;
            //EVM.inclusions = e.inclusions;
            //EVM.startDate = e.startDate;
            //EVM.actualDate = e.actualDate;
            //EVM.endDate = e.endDate;

            //if (EVM == null)
            //{
            //    return HttpNotFound();
            //}
            Event e = ES.GetById(id);
            int idUS = e.userId;

            User user = US.GetById(idUS);
            string username = user.firstName + "   " + user.lastName;
            string usermail = user.email;
           
            string eventname = e.title;

            ViewBag.usersname = username;
            ViewBag.usersmail = usermail;
            ViewBag.evs = eventname;

            BookingViewModels BVM = new BookingViewModels();
            BVM.qrcodeUrl = user.email;
            return View(BVM);

        }


        //POST: Event/Paricipate/1
        [HttpPost]
        public ActionResult Participate(int id, EventViewModels EVM)
        {
            
            Event e = ES.GetById(id);
            if (e.nbParticipant > 0)
            {
                int idUS = e.userId;
                User usr = US.GetById(idUS);
                Booking b = new Booking();
                b.eventId = id;
                b.userId = 1;
                b.qrcodeUrl = usr.email;
                ES.EventParticipation(b);
                //  BS.Add(b);
                ES.Commit();

                e.nbParticipant--;
                ES.Update(e);
                ES.Commit();


                PrintDocument imp = new PrintDocument();
                imp.DocumentName = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\fichier1.pdf";
                string vue = imp.ToString();
                imp.Print();



                //Process proc = new Process();
                //proc.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                //proc.StartInfo.Verb = "print";
                //string pdfFileName = Environment.GetFolderPath(Environment.SpecialFolder.ApplicaC:\Users\Asus\Documents\Esprit\4éme Année\PI\Project.net\ArtisticShowroomV2\Services\IBookingService.cstionData) + "\\fichier1.pdf";
                //proc.StartInfo.FileName = @"C:\Program Files (x86)\Adobe\Reader 10.0\Reader\AcroRd32.exe";
                //proc.StartInfo.Arguments = @"/p /h " + pdfFileName;
                //proc.StartInfo.UseShellExecute = false;
                //proc.StartInfo.CreateNoWindow = true;
                //proc.Start();
                //proc.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
                //if (proc.HasExited == false)
                //{
                //    proc.WaitForExit(1000);
                //    //proc.Kill();
                //}
                //proc.EnableRaisingEvents = true;
                ////proc.Kill();
                //////  AcroRd32.exe
                ////proc.CloseMainWindow();
                ////proc.Close();

                return RedirectToAction("Index") ;

            }
            else
            {
                ViewBag.msg = "No more places available";

                return View();
            }

        }
       

        //GET : PassedEvent
        public ActionResult GetPassedEvent()
        {
            List<EventViewModels> eventList = new List<EventViewModels>();

            foreach (var item in ES.GetAll())
            {
                if (item.endDate < DateTime.Now)

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
    .button {
    background-color: #0080B0; /* Green */
    border-radius: 12px;
    color: white;
    padding: 10px 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 11px;
    margin: 5px 2px;
    cursor: pointer;
    }
        </style>
    <title>@Page.Title</title>
    @RenderSection("head", required: false)





    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Marqa Portfolio</title>
    <meta name="description" content="tottaly responsive personal portfolio template" />
    <meta name="keywords" content="responsive, template, portfolio, html, css, javascript" />
    <meta name="author" content="Ahmed Beheiry" />
    <!-- Open Sans Google font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <!-- Raleway Google font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:700">
    <!-- Favicons -->
    <link rel="shortcut icon" href="@Url.Content("~/Content/MyTemplate/img/favico/")marqa.ico">
    <link rel="apple-touch-icon" sizes="60x60" href="@Url.Content("~/Content/MyTemplate/img/favico/")apple-icon-60x60.png">
    <!-- Fontawesome fonts css file -->
    <link rel="stylesheet" href="@Url.Content("~/Content/MyTemplate/css/")font-awesome.min.css">
    <!-- Animate.css file -->
    <link rel="stylesheet" href="@Url.Content("~/Content/MyTemplate/css/")animate.css">
    <!-- Owl carousel css file -->
    <link rel="stylesheet" href="@Url.Content("~/Content/MyTemplate/css/")owl.carousel.css">
    <!-- Bootstrap file -->
    <link rel="stylesheet" href="@Url.Content("~/Content/MyTemplate/css/")bootstrap.min.css">
    <!-- Custom styles css file -->
    <link rel="stylesheet" href="@Url.Content("~/Content/MyTemplate/css/")style.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->



</head>


<body>
    <!-- Start Header Section -->
    <div class="header" id="header">
        <div id="large-header" class="large-header">
            <canvas id="demo-canvas"></canvas>
            <div class="content center">
                <div class="container">
                    <p>Hello, It's </p>
                    <h1>Artistic Showroom</h1>
                    <a href="#about-me">Read more</a>
                    <a href="@Url.Action("Index", "Event")">my Events</a>
                </div> <!-- End container -->
            </div>
            <div class="mouse" id="mouse"></div>  <!-- Mouse Icon -->
        </div>
    </div>
    <!-- End Header Section -->
    <!-- Start Side Menu -->
    <nav id="top-nav">
        <div class="logo center"><a href="#">Marqa</a></div> <!-- LOGO -->
        <div class="menu" id="menu">
            <span class="bar b1"></span>
            <span class="bar b2"></span>
            <span class="bar b3"></span>
        </div>
        <div class="side-menu" id="side-menu">
            <!-- Menu items -->
            <a href=@Url.Action("Index", "Calendar")>Calendar</a>
            <a href="@Url.Action("Index", "Event")">Current Event List</a>
            <a href=@Url.Action("Create", "Event")>Add new Event</a>
            <a href=@Url.Action("BestEvent", "Event")>Best Event</a>
            <a href=@Url.Action("GetPassedEvent", "Event")>Passed Event</a>
            <a href=@Url.Action("GetListEvent", "Booking")>Participations</a>

        </div>
    </nav>
    <!-- End Side Menu -->

    <div class="container body-content">

        @RenderBody()

    </div>


    <!-- Start Footer Section -->
    <div class="footer center">
        <div class="container">
            <div class="row">
                <div class="follow-me">follow me</div>
                <div class="col-md-12 col-xs-12 links">
                    <!-- Social links -->
                    <div class="icon-wrapper center">
                        <!-- Facebook Link -->
                        <a href="#" class="icon fb">
                            <i class="fa fa-facebook"></i>
                            <i class="fa fa-facebook"></i>
                        </a>
                        <!-- Twitter Link -->
                        <a href="#" class="icon tw">
                            <i class="fa fa-twitter"></i>
                            <i class="fa fa-twitter"></i>
                        </a>
                        <!-- Github Link -->
                        <a href="#" class="icon gh">
                            <i class="fa fa-github"></i>
                            <i class="fa fa-github"></i>
                        </a>
                        <!-- Google Plus Link -->
                        <a href="#" class="icon gp">
                            <i class="fa fa-google-plus"></i>
                            <i class="fa fa-google-plus"></i>
                        </a>
                        <!-- Linkedin Link -->
                        <a href="#" class="icon lin">
                            <i class="fa fa-linkedin"></i>
                            <i class="fa fa-linkedin"></i>
                        </a>
                        <!-- Pinterest Link -->
                        <a href="#" class="icon pin">
                            <i class="fa fa-pinterest"></i>
                            <i class="fa fa-pinterest"></i>
                        </a>
                    </div>
                </div>
                <div class="col-md12 col-xs-12 copyright">
                    <h6>&copy; Marqa 2016 All RightsReserved. Designed by Ahmed Beheiry</h6>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer Section -->
    <!-- Start To Top button -->
    <div class="back-to-top center">
        <i class="fa fa-long-arrow-up"></i>
    </div>
    <!-- End To Top button -->
    <!-- Start scroll percentage -->
    <div id="scroll"></div>
    <!-- End scroll percentage -->
    <!-- Including jQuery file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery-1.12.1.min.js"></script>
    <!-- Including jQuery.appear file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery.appear.js"></script>
    <!-- Bootstrap js file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")bootstrap.min.js"></script>
    <!-- easy pie chart -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery.easypiechart.min.js"></script>
    <!-- NiceScroll plugin -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery.nicescroll.min.js"></script>
    <!-- animate numbers plugin -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery.animatenumber.min.js"></script>
    <!-- Horizontal bar chart -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")bars.js"></script>
    <!-- mixitup plugin -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")jquery.mixitup.min.js"></script>
    <!-- animated background header -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")tweenlite.min.js"></script>
    <!-- form validation file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")validator.min.js"></script>
    <!-- Owl carousel js file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")owl.carousel.min.js"></script>
    <!-- Google Map -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJOx2cEs3x3dTSubqABijclN_3uEmL7f8"></script>
    <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script> -->
    <!-- Custom file  -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")plugins.js"></script>
    <!-- Wow.js file -->
    <script src="@Url.Content("~/Content/MyTemplate/js/")wow.min.js"></script>
    <script>
			new WOW().init();
    </script>



    <script src="~/Scripts/jquery-2.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @Scripts.Render("~/Scripts/jquery-2.0.0.min.js")

    @RenderSection("scripts", false)
</body>
</html>